apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80        # Exposed port on the service (Kubernetes)
      targetPort: 80  # Port that nginx container listens on
      nodePort: 31297 # Specific NodePort for Kind (match this in Kind config)
